name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - test
      - prod

permissions:
  contents: write # Ensure the token has write permissions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Create .nojekyll file
        run: echo "" > .nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # Use gh-pages branch for deployment
          publish_dir: ./build # Specify the build directory
          destination_dir: ${{ github.ref_name }} # Deploy to a directory named after the branch
